// Features.jsx — Technical feature showcase for Screenloop Pro
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { SiteHeader, SiteFooter } from '../components';
import {
  FilmStrip, MonitorPlay, SpeakerSimpleHigh, LockSimple, PaintBrush,
  ChartBar, QrCode, Lightning, Users, ShieldCheck, Check,
  RocketLaunch, PictureInPicture
} from '../components/icons';
import { staggerContainer, fadeInUp } from '../hooks/useScrollReveal';
import { generateRoomId, generateRoomKey } from '../utils';

const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'media', label: 'Streaming & Audio' },
  { id: 'security', label: 'Privacy' },
  { id: 'interactive', label: 'Interactive' },
];

const FEATURES = [
  {
    category: 'media',
    icon: <SpeakerSimpleHigh size={30} weight="duotone" />,
    badge: 'Audio',
    title: 'Audio That Doesn\'t Ruin Movies',
    desc: 'Most screen-sharing tools apply echo cancellation and voice filters by default. We skip that. Film scores, surround mixes, and quiet dialogue come through unprocessed so they sound the way the director intended.',
    specs: ['Echo cancellation disabled', 'Full stereo pass-through', 'Optional volume boost'],
  },
  {
    category: 'media',
    icon: <MonitorPlay size={30} weight="duotone" />,
    badge: 'Streaming',
    title: 'Direct Peer-to-Peer Screen Sharing',
    desc: 'Screen and audio frames travel directly between browsers via WebRTC — they don\'t pass through a central server. This means less buffering, lower latency, and no server bandwidth bill eating into performance.',
    specs: ['Up to 1080p60 (1440p on strong connections)', 'Adaptive bitrate', 'No relay server needed'],
  },
  {
    category: 'security',
    icon: <LockSimple size={30} weight="duotone" />,
    badge: 'Encryption',
    title: 'Chat Messages Encrypted in Your Browser',
    desc: 'A 256-bit AES-GCM key is generated by the host and placed in the URL hash fragment. Browsers never send hash fragments in HTTP requests, so the server can\'t read your messages even if it wanted to.',
    specs: ['AES-256-GCM via Web Crypto API', 'Key never leaves the URL', 'Server sees only ciphertext'],
  },
  {
    category: 'interactive',
    icon: <PaintBrush size={30} weight="duotone" />,
    badge: 'Annotations',
    title: 'Live Drawing Over the Stream',
    desc: 'Annotate the video in real time with pen strokes, highlighters, and a laser pointer — synchronized across all viewers. Useful for pointing things out during a movie or walking someone through a screen.',
    specs: ['Real-time canvas sync', 'Pen, highlighter, eraser', 'Laser pointer overlay'],
  },
  {
    category: 'interactive',
    icon: <Users size={30} weight="duotone" />,
    badge: 'Avatars',
    title: 'No-Account Avatars',
    desc: 'Pick a style (male, female, or neutral) when you join and you get a generated avatar — no signup, no profile picture upload, no data stored about you.',
    specs: ['Generated client-side via DiceBear', 'No profile data stored', 'Three style options'],
  },
  {
    category: 'interactive',
    icon: <ChartBar size={30} weight="duotone" />,
    badge: 'Diagnostics',
    title: 'Stream Quality Dashboard',
    desc: 'A toggleable overlay that shows live connection stats: framerate, bitrate, packet loss, and round-trip ping. Helpful for figuring out whether a problem is your Wi-Fi or something else.',
    specs: ['FPS and bitrate display', 'Packet loss percentage', 'Ping measurement'],
  },
  {
    category: 'security',
    icon: <ShieldCheck size={30} weight="duotone" />,
    badge: 'Access',
    title: 'Optional PIN Protection',
    desc: 'Set a password on your room to keep random people out. Failed attempts are rate-limited so brute-force guessing isn\'t practical.',
    specs: ['In-memory PIN check', 'Rate-limited attempts', 'Host can kick users'],
  },
  {
    category: 'media',
    icon: <QrCode size={30} weight="duotone" />,
    badge: 'Mobile',
    title: 'QR Code for Quick Mobile Join',
    desc: 'Generate a QR code on screen that friends can scan with their phone camera. The code is rendered locally in your browser — no third-party API is contacted.',
    specs: ['HTML5 Canvas rendering', 'Generated client-side', 'Works with native camera apps'],
  },
  {
    category: 'media',
    icon: <PictureInPicture size={30} weight="duotone" />,
    badge: 'Playback',
    title: 'Picture-in-Picture & Fullscreen',
    desc: 'Pop the stream into a floating window or go fullscreen with auto-hiding controls. Screen Wake Lock keeps your laptop from sleeping during long movies.',
    specs: ['Standard HTML5 PiP', 'Screen Wake Lock API', 'Fullscreen (press F)'],
  },
];

export default function Features() {
  const navigate = useNavigate();
  const [activeCategory, setActiveCategory] = useState('all');
  const [isLaunching, setIsLaunching] = useState(false);

  const filteredFeatures = activeCategory === 'all'
    ? FEATURES
    : FEATURES.filter((f) => f.category === activeCategory);

  const handleLaunch = async () => {
    try {
      setIsLaunching(true);
      const roomId = generateRoomId();
      const rawKey = await generateRoomKey();
      navigate(`/room/${roomId}?host=true${rawKey ? '#' + rawKey : ''}`, { state: { isCreator: true } });
    } catch (err) {
      console.error('Launch failed:', err);
      navigate('/');
    } finally {
      setIsLaunching(false);
    }
  };

  return (
    <div className="page-wrapper">
      <SiteHeader />

      <main className="features-page-content">
        <motion.div
          className="features-container"
          variants={staggerContainer}
          initial="hidden"
          animate="visible"
        >
          {/* Hero */}
          <motion.section className="page-hero" variants={fadeInUp}>
            <span className="about-eyebrow">Features</span>
            <h1 className="page-hero-title">
              What You Actually Get
            </h1>
            <p className="page-hero-subtitle">
              A practical overview of how Screenloop handles streaming, audio, encryption, and collaboration.
            </p>
          </motion.section>

          {/* Category Filter */}
          <motion.div className="features-filter-bar" variants={fadeInUp}>
            {CATEGORIES.map((cat) => (
              <button
                key={cat.id}
                type="button"
                className={`filter-btn ${activeCategory === cat.id ? 'active' : ''}`}
                onClick={() => setActiveCategory(cat.id)}
              >
                {cat.label}
              </button>
            ))}
          </motion.div>

          {/* Features Bento Grid */}
          <motion.div className="features-bento-grid" variants={staggerContainer}>
            {filteredFeatures.map((feature, idx) => (
              <motion.div
                key={idx}
                className="feature-card-pro glass-card"
                variants={fadeInUp}
                whileHover={{ y: -4 }}
              >
                <div className="feature-card-header">
                  <div className="feature-icon-box">{feature.icon}</div>
                  <span className="feature-badge">{feature.badge}</span>
                </div>
                <h2 className="feature-card-title">{feature.title}</h2>
                <p className="feature-card-desc">{feature.desc}</p>
                <div className="feature-specs-list">
                  {feature.specs.map((spec, sIdx) => (
                    <span key={sIdx} className="spec-tag">
                      <Check size={12} weight="bold" /> {spec}
                    </span>
                  ))}
                </div>
              </motion.div>
            ))}
          </motion.div>

          {/* Quick Launch CTA */}
          <motion.section className="help-section" variants={fadeInUp}>
            <div className="section-header-centered">
              <h2 className="section-title">Want to try it out?</h2>
              <p className="section-desc">
                Create a room, share the link, and see how it works with your group.
              </p>
              <button
                type="button"
                className="btn btn-primary btn-sm"
                onClick={handleLaunch}
                disabled={isLaunching}
                style={{ marginTop: 'var(--space-3)' }}
              >
                {isLaunching ? 'Preparing Room…' : 'Launch a Room'}
              </button>
            </div>
          </motion.section>
        </motion.div>
      </main>

      <SiteFooter />
    </div>
  );
}
